// This file is auto-generated by scripts/export_autocss_lab.py
// Do not edit by hand.

export const GENERATED_AUTO_CSS_CASES = [
  {
    "id": "lay2",
    "sourceName": "lay2.jpg",
    "dimensions": {
      "width": 1280,
      "height": 720
    },
    "stages": {
      "input": "/images/autocss-lab/lay2/input.png",
      "binarized": "/images/autocss-lab/lay2/binarized.png",
      "cleanup": "/images/autocss-lab/lay2/cleanup.png",
      "edges": "/images/autocss-lab/lay2/edges.png",
      "contours": "/images/autocss-lab/lay2/contours.png",
      "scaffold": "/images/autocss-lab/lay2/scaffold.png"
    },
    "tree": [
      {
        "id": "5",
        "bbox": {
          "x": 188,
          "y": 55,
          "w": 953,
          "h": 611
        },
        "depth": 0,
        "children": [
          {
            "id": "7",
            "bbox": {
              "x": 514,
              "y": 487,
              "w": 184,
              "h": 113
            },
            "depth": 2,
            "children": [
              {
                "id": "9",
                "bbox": {
                  "x": 534,
                  "y": 521,
                  "w": 51,
                  "h": 42
                },
                "depth": 4,
                "children": []
              },
              {
                "id": "13",
                "bbox": {
                  "x": 607,
                  "y": 514,
                  "w": 63,
                  "h": 45
                },
                "depth": 4,
                "children": [
                  {
                    "id": "15",
                    "bbox": {
                      "x": 621,
                      "y": 525,
                      "w": 37,
                      "h": 22
                    },
                    "depth": 6,
                    "children": []
                  }
                ]
              },
              {
                "id": "16",
                "bbox": {
                  "x": 528,
                  "y": 499,
                  "w": 158,
                  "h": 88
                },
                "depth": 4,
                "children": []
              }
            ]
          },
          {
            "id": "18",
            "bbox": {
              "x": 735,
              "y": 476,
              "w": 290,
              "h": 151
            },
            "depth": 2,
            "children": [
              {
                "id": "20",
                "bbox": {
                  "x": 747,
                  "y": 488,
                  "w": 265,
                  "h": 128
                },
                "depth": 4,
                "children": [
                  {
                    "id": "22",
                    "bbox": {
                      "x": 761,
                      "y": 515,
                      "w": 64,
                      "h": 67
                    },
                    "depth": 6,
                    "children": [
                      {
                        "id": "24",
                        "bbox": {
                          "x": 773,
                          "y": 527,
                          "w": 39,
                          "h": 44
                        },
                        "depth": 8,
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "26",
                    "bbox": {
                      "x": 844,
                      "y": 512,
                      "w": 73,
                      "h": 66
                    },
                    "depth": 6,
                    "children": [
                      {
                        "id": "28",
                        "bbox": {
                          "x": 861,
                          "y": 524,
                          "w": 45,
                          "h": 41
                        },
                        "depth": 8,
                        "children": []
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "30",
            "bbox": {
              "x": 509,
              "y": 371,
              "w": 496,
              "h": 99
            },
            "depth": 2,
            "children": [
              {
                "id": "32",
                "bbox": {
                  "x": 522,
                  "y": 382,
                  "w": 470,
                  "h": 74
                },
                "depth": 4,
                "children": []
              }
            ]
          },
          {
            "id": "34",
            "bbox": {
              "x": 258,
              "y": 250,
              "w": 209,
              "h": 375
            },
            "depth": 2,
            "children": [
              {
                "id": "36",
                "bbox": {
                  "x": 272,
                  "y": 262,
                  "w": 183,
                  "h": 351
                },
                "depth": 4,
                "children": [
                  {
                    "id": "38",
                    "bbox": {
                      "x": 320,
                      "y": 488,
                      "w": 114,
                      "h": 69
                    },
                    "depth": 6,
                    "children": [
                      {
                        "id": "40",
                        "bbox": {
                          "x": 331,
                          "y": 500,
                          "w": 92,
                          "h": 45
                        },
                        "depth": 8,
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "42",
                    "bbox": {
                      "x": 318,
                      "y": 389,
                      "w": 101,
                      "h": 69
                    },
                    "depth": 6,
                    "children": [
                      {
                        "id": "44",
                        "bbox": {
                          "x": 333,
                          "y": 401,
                          "w": 74,
                          "h": 44
                        },
                        "depth": 8,
                        "children": []
                      }
                    ]
                  },
                  {
                    "id": "46",
                    "bbox": {
                      "x": 307,
                      "y": 304,
                      "w": 104,
                      "h": 61
                    },
                    "depth": 6,
                    "children": [
                      {
                        "id": "48",
                        "bbox": {
                          "x": 320,
                          "y": 315,
                          "w": 78,
                          "h": 39
                        },
                        "depth": 8,
                        "children": []
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "50",
            "bbox": {
              "x": 497,
              "y": 229,
              "w": 499,
              "h": 113
            },
            "depth": 2,
            "children": [
              {
                "id": "52",
                "bbox": {
                  "x": 511,
                  "y": 242,
                  "w": 471,
                  "h": 88
                },
                "depth": 4,
                "children": []
              }
            ]
          },
          {
            "id": "56",
            "bbox": {
              "x": 247,
              "y": 114,
              "w": 815,
              "h": 96
            },
            "depth": 2,
            "children": []
          }
        ]
      },
      {
        "id": "57",
        "bbox": {
          "x": 174,
          "y": 44,
          "w": 979,
          "h": 634
        },
        "depth": 0,
        "children": []
      }
    ],
    "treeAsset": "/images/autocss-lab/lay2/tree.json",
    "treeLines": [
      "\u251c\u2500 bbox(188, 55, 953, 611)",
      "\u2502  \u251c\u2500 bbox(514, 487, 184, 113)",
      "\u2502  \u2502  \u251c\u2500 bbox(534, 521, 51, 42)",
      "\u2502  \u2502  \u251c\u2500 bbox(607, 514, 63, 45)",
      "\u2502  \u2502  \u2502  \u2514\u2500 bbox(621, 525, 37, 22)",
      "\u2502  \u2502  \u2514\u2500 bbox(528, 499, 158, 88)",
      "\u2502  \u251c\u2500 bbox(735, 476, 290, 151)",
      "\u2502  \u2502  \u2514\u2500 bbox(747, 488, 265, 128)",
      "\u2502  \u2502     \u251c\u2500 bbox(761, 515, 64, 67)",
      "\u2502  \u2502     \u2502  \u2514\u2500 bbox(773, 527, 39, 44)",
      "\u2502  \u2502     \u2514\u2500 bbox(844, 512, 73, 66)",
      "\u2502  \u2502        \u2514\u2500 bbox(861, 524, 45, 41)",
      "\u2502  \u251c\u2500 bbox(509, 371, 496, 99)",
      "\u2502  \u2502  \u2514\u2500 bbox(522, 382, 470, 74)",
      "\u2502  \u251c\u2500 bbox(258, 250, 209, 375)",
      "\u2502  \u2502  \u2514\u2500 bbox(272, 262, 183, 351)",
      "\u2502  \u2502     \u251c\u2500 bbox(320, 488, 114, 69)",
      "\u2502  \u2502     \u2502  \u2514\u2500 bbox(331, 500, 92, 45)",
      "\u2502  \u2502     \u251c\u2500 bbox(318, 389, 101, 69)",
      "\u2502  \u2502     \u2502  \u2514\u2500 bbox(333, 401, 74, 44)",
      "\u2502  \u2502     \u2514\u2500 bbox(307, 304, 104, 61)",
      "\u2502  \u2502        \u2514\u2500 bbox(320, 315, 78, 39)",
      "\u2502  \u251c\u2500 bbox(497, 229, 499, 113)",
      "\u2502  \u2502  \u2514\u2500 bbox(511, 242, 471, 88)",
      "\u2502  \u2514\u2500 bbox(247, 114, 815, 96)",
      "\u2514\u2500 bbox(174, 44, 979, 634)"
    ],
    "domAsset": "/images/autocss-lab/lay2/dom.txt",
    "domText": "<div>\n  <div>\n    <p>content</p>\n    <div>\n      <p>content</p>\n    </div>\n    <p>content</p>\n  </div>\n  <div>\n    <div>\n      <div>\n        <p>content</p>\n      </div>\n      <div>\n        <p>content</p>\n      </div>\n    </div>\n  </div>\n  <div>\n    <p>content</p>\n  </div>\n  <div>\n    <div>\n      <div>\n        <p>content</p>\n      </div>\n      <div>\n        <p>content</p>\n      </div>\n      <div>\n        <p>content</p>\n      </div>\n    </div>\n  </div>\n  <div>\n    <p>content</p>\n  </div>\n  <p>content</p>\n</div>\n<p>content</p>\n",
    "contourCount": 58
  },
  {
    "id": "lay4",
    "sourceName": "lay4.jpg",
    "dimensions": {
      "width": 1280,
      "height": 720
    },
    "stages": {
      "input": "/images/autocss-lab/lay4/input.png",
      "binarized": "/images/autocss-lab/lay4/binarized.png",
      "cleanup": "/images/autocss-lab/lay4/cleanup.png",
      "edges": "/images/autocss-lab/lay4/edges.png",
      "contours": "/images/autocss-lab/lay4/contours.png",
      "scaffold": "/images/autocss-lab/lay4/scaffold.png"
    },
    "tree": [
      {
        "id": "7",
        "bbox": {
          "x": 882,
          "y": 227,
          "w": 232,
          "h": 178
        },
        "depth": 0,
        "children": [
          {
            "id": "9",
            "bbox": {
              "x": 894,
              "y": 238,
              "w": 208,
              "h": 156
            },
            "depth": 2,
            "children": []
          }
        ]
      },
      {
        "id": "11",
        "bbox": {
          "x": 218,
          "y": 164,
          "w": 581,
          "h": 370
        },
        "depth": 0,
        "children": [
          {
            "id": "13",
            "bbox": {
              "x": 237,
              "y": 175,
              "w": 551,
              "h": 348
            },
            "depth": 2,
            "children": []
          }
        ]
      }
    ],
    "treeAsset": "/images/autocss-lab/lay4/tree.json",
    "treeLines": [
      "\u251c\u2500 bbox(882, 227, 232, 178)",
      "\u2502  \u2514\u2500 bbox(894, 238, 208, 156)",
      "\u2514\u2500 bbox(218, 164, 581, 370)",
      "   \u2514\u2500 bbox(237, 175, 551, 348)"
    ],
    "domAsset": "/images/autocss-lab/lay4/dom.txt",
    "domText": "<div>\n  <p>content</p>\n</div>\n<div>\n  <p>content</p>\n</div>\n",
    "contourCount": 14
  },
  {
    "id": "newlay",
    "sourceName": "newlay.jpg",
    "dimensions": {
      "width": 1280,
      "height": 720
    },
    "stages": {
      "input": "/images/autocss-lab/newlay/input.png",
      "binarized": "/images/autocss-lab/newlay/binarized.png",
      "cleanup": "/images/autocss-lab/newlay/cleanup.png",
      "edges": "/images/autocss-lab/newlay/edges.png",
      "contours": "/images/autocss-lab/newlay/contours.png",
      "scaffold": "/images/autocss-lab/newlay/scaffold.png"
    },
    "tree": [
      {
        "id": "1",
        "bbox": {
          "x": 832,
          "y": 413,
          "w": 279,
          "h": 205
        },
        "depth": 0,
        "children": [
          {
            "id": "3",
            "bbox": {
              "x": 846,
              "y": 426,
              "w": 251,
              "h": 180
            },
            "depth": 2,
            "children": []
          }
        ]
      },
      {
        "id": "5",
        "bbox": {
          "x": 214,
          "y": 267,
          "w": 261,
          "h": 89
        },
        "depth": 0,
        "children": []
      },
      {
        "id": "7",
        "bbox": {
          "x": 838,
          "y": 263,
          "w": 148,
          "h": 98
        },
        "depth": 0,
        "children": [
          {
            "id": "9",
            "bbox": {
              "x": 852,
              "y": 277,
              "w": 122,
              "h": 69
            },
            "depth": 2,
            "children": []
          }
        ]
      },
      {
        "id": "10",
        "bbox": {
          "x": 203,
          "y": 256,
          "w": 284,
          "h": 111
        },
        "depth": 0,
        "children": []
      },
      {
        "id": "12",
        "bbox": {
          "x": 571,
          "y": 244,
          "w": 211,
          "h": 180
        },
        "depth": 0,
        "children": [
          {
            "id": "14",
            "bbox": {
              "x": 586,
              "y": 256,
              "w": 181,
              "h": 156
            },
            "depth": 2,
            "children": []
          }
        ]
      },
      {
        "id": "18",
        "bbox": {
          "x": 325,
          "y": 77,
          "w": 765,
          "h": 103
        },
        "depth": 0,
        "children": [
          {
            "id": "20",
            "bbox": {
              "x": 347,
              "y": 88,
              "w": 728,
              "h": 80
            },
            "depth": 2,
            "children": []
          }
        ]
      }
    ],
    "treeAsset": "/images/autocss-lab/newlay/tree.json",
    "treeLines": [
      "\u251c\u2500 bbox(832, 413, 279, 205)",
      "\u2502  \u2514\u2500 bbox(846, 426, 251, 180)",
      "\u251c\u2500 bbox(214, 267, 261, 89)",
      "\u251c\u2500 bbox(838, 263, 148, 98)",
      "\u2502  \u2514\u2500 bbox(852, 277, 122, 69)",
      "\u251c\u2500 bbox(203, 256, 284, 111)",
      "\u251c\u2500 bbox(571, 244, 211, 180)",
      "\u2502  \u2514\u2500 bbox(586, 256, 181, 156)",
      "\u2514\u2500 bbox(325, 77, 765, 103)",
      "   \u2514\u2500 bbox(347, 88, 728, 80)"
    ],
    "domAsset": "/images/autocss-lab/newlay/dom.txt",
    "domText": "<div>\n  <p>content</p>\n</div>\n<p>content</p>\n<div>\n  <p>content</p>\n</div>\n<p>content</p>\n<div>\n  <p>content</p>\n</div>\n<div>\n  <p>content</p>\n</div>\n",
    "contourCount": 21
  }
] as const;
